image:
  repository: registry.gitlab.com/<<TU_GRUPO>>/rul-fastapi
  tag: 1.0-arm64
  pullPolicy: IfNotPresent

service:
  name: rul-fastapi
  port: 80
  targetPort: 8080

nodeSelector:
  kubernetes.io/hostname: kb-edge01
  kubernetes.io/arch: arm64

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1500m
    memory: 1Gi

redis:
  url: redis://redis-edge-master.mlops-edge.svc.cluster.local:6379

ingress:
  enabled: true
  className: traefik
  host: rul-edge.local
  path: /
